apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qubernetes
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app: qpu-proxy
  kustomize.component: qpu-proxy
  app.kubernetes.io/name: qpu-proxy
  app.kubernetes.io/component: qpu-proxy
configMapGenerator:
  - name: cortex-config
    files:
      - configmaps/config.json
secretGenerator:
  - name: cortex-tokens
    files:
      - secrets/tokens.json
