apiVersion: v1
kind: Service
metadata:
  name: qpu-proxy-service
spec:
  selector:
    app: qpu-proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: qpu-proxy-svc